web: gunicorn TemplateRoot:app

worker: gunicorn UpdateCompanyProfile.py
worker: gunicorn sqlwrapper.py
worker: gunicorn UpdateProfileRecord.py
worker: gunicorn UpdateProfilePreference.py
worker: gunicorn UpdateProfileNotes.py
worker: gunicorn UpdateProfileCreditcard.py
worker: gunicorn UpdateNegotiatedRate.py
worker: gunicorn UpdateIndividualProfile.py
worker: gunicorn QueryProfileRecord.py
worker: gunicorn QueryNegotiatedRate.py
worker: gunicorn DeleteProfileRecord.py
worker: gunicorn UpdateProfileCreditcardRecord.py
worker: gunicorn UpdateProfileNegotiatedRateRecord.py
worker: gunicorn UpdateProfileNotesRecord.py
worker: gunicorn UpdateProfilePreferencenew.py
worker: gunicorn QueryProfileRecordAll.py
worker: gunicorn MergeProfile.py
worker: gunicorn DeleteProfileRecordAll.py
worker: gunicorn QueryProfileHistory.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryAlertReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryDepositrule.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryFixedChargesReservation.py
worker: gunicorn Hotel_RES_Get_Select_QueryReservationActivitylog.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryWaitlistReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_RoomUnassign.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateAlertReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateDeposit.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateFixedChargesReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateFixedRateReservation.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateGuestPrivileges.py
worker: gunicorn Hotel_RES_Post_Insert_UpdateGuestTraces.py
worker: gunicorn HOTEL_RES_POST_INSERT_UpdateNewReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_WaitlistReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateDeposit.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateFixedChargesReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateFixedRateReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateReservation.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateReservationAlert.py
worker: gunicorn HOTEL_RES_POST_UPDATE_UpdateWaitlistReservation.py
worker: gunicorn Hotel_RES_Post_Select_Queryreservation.py
worker: gunicorn HOTEL_FD_POST_INSERT_UpdateQueueRreservation.py
worker: gunicorn HOTEL_FD_GET_SELECT_QueryQueueReservation.py
worker: gunicorn Hotel_RM_Post_Insert_Updateroom.py
worker: gunicorn Hotel_RM_Post_Select_Queryhousekeepinglist.py
worker: gunicorn Hotel_RM_Post_Select_Queryoutoforderservice.py
worker: gunicorn Hotel_RM_Post_Select_Queryroommaintenance.py
worker: gunicorn Hotel_RM_Post_Update_Updateroomdiscrepancies.py
worker: gunicorn Hotel_RM_Post_Update_Updateroomstatus.py
worker: gunicorn AMAZON_RESERVATION_LAMBDA_LEX.py
worker: gunicorn profilecity.py
worker: gunicorn profileinsertvalue.py
worker: gunicorn HOTEL_RES_POST_INSERT_InsertReservationValue.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryReservationValue.py
worker: gunicorn RoomManagementDropdown.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomList.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomCondition.py
worker: gunicorn Hotel_Rm_Post_Update_UpdateRoomCondition.py
worker: gunicorn profilesearch.py
worker: gunicorn RoomManagementDropdownInsert.py
worker: gunicorn Hotel_RES_POST_SELECT_QueryFutureReservation.py
worker: gunicorn QueryReservationSearch.py
worker: gunicorn HOTEL_RES_POST_SELECT_QueryHistoryReservation.py
worker: gunicorn HOTEL_RES_GET_SELECT_QueryFixedRateReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_CancelReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_ReinstateReservation.py
worker: gunicorn HOTEL_RES_POST_SELECT_QueryArrivalFromToReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_WaitlistReason.py
worker: gunicorn HOTEL_RES_POST_INSERT_AcceptWaitlistReservation.py
worker: gunicorn HOTEL_RES_POST_INSERT_ReservationCreditcard.py
worker: gunicorn HOTEL_RES_POST_DELETE_DeleteReservation.py
worker: gunicorn HOTEL_FD_POST_INSERT_RoomAssign.py
worker: gunicorn HOTEL_FD_POST_UPDATE_CheckinGuestArrivals.py
worker: gunicorn Hotel_RES_Post_Update_TracesResloved.py
worker: gunicorn HOTEL_FD_GET_SELECT_QueryTracesActivityLog.py
worker: gunicorn HOTEL_RES_POST_UPDATE_RoomMove.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomList.py
worker: gunicorn Hotel_Rm_Post_Select_QueryroomStatistics.py
worker: gunicorn Hotel_Rm_Post_Select_QueryRoomDiscrepancies.py
worker: gunicorn Hotel_Rm_Post_Insert_UpdateGuestServiceStatus.py
worker: gunicorn HOTEL_FD_POST_SELECT_QueryRoomAssignment.py
worker: gunicorn HOTEL_REVENUE_MANAGEMENT_POST_SELECT.py
worker: gunicorn HOTEL_REVENUE_MANAGEMENT_POST_INSERT_RATECATEGORY.py
worker: gunicorn HOTEL_REM_POST_SELECT_QueryRatecode.py
worker: gunicorn HOTEL_REM_POST_INSERT_UpdateRatecodeSetup.py
worker: gunicorn HOTEL_REM_POST_DELETE.py
worker: gunicorn HOTEL_REM_POST_UPDATE_UpdateRatecodeSetup.py
worker: gunicorn HOTEL_REM_POST_SELECT_UpdateRatecodeSetup.py
worker: gunicorn HOTEL_CASH_SELECT_POSTING_WINDOW.py
worker: gunicorn HOTEL_CASH_SELECT_BILLING_CURRENCY.py
worker: gunicorn HOTEL_CASH_RESERVATION_STATUS.py
worker: gunicorn HOTEL_CASH_RESERVATION_BALANCE.py
worker: gunicorn HOTEL_CASH_POSTING_WINDOW.py
worker: gunicorn HOTEL_CASH_INSERT_BILLING_CURRENCY.py
worker: gunicorn HOTEL_CASH_BILLING_POST_SELECT_ID.py
worker: gunicorn HOTEL_CASH_BILLING_CODE_SELECT.py
worker: gunicorn HOTEL_CASH_BILLING_CODE_INSERT.py
worker: gunicorn HOTEL_CAH_POST_UPDATE_UPDATEGUESTBILLING.py
worker: gunicorn HOTEL_CAH_POST_UPDATE_TransfertoAnotherWindow.py
worker: gunicorn HOTEL_CAH_POST_UPDATE_TransfertoAnotherRoom.py 
worker: gunicorn HOTEL_CAH_POST_POSTING_PAYMENT_INSERT.py
worker: gunicorn HOTEL_CAH_POST_POSTING_PAYMENT.py
worker: gunicorn HOTEL_CAH_POST_POSTING_HISTORY_LOG.py
worker: gunicorn HOTEL_CAH_POST_INSERT_UPDATEPOSTINGPAYMENT.py
worker: gunicorn HOTEL_CAH_POST_INSERT_UPDATEGUESTBILLING.py
worker: gunicorn HOTEL_CAH_POST_FOLIO_HISTORY.py
worker: gunicorn HOTEL_CAH_POST_CASH_CHECK_OUT.py
worker: gunicorn HOTEL_CAH_GET_SELECT_QUERYGUESTBILLING.py
worker: gunicorn HOTEL_BBL_GET_SELECT_BusinessBlockSearch.py
worker: gunicorn HOTEL_BBL_POST_INSERT_Business_Block_Notes.py
worker: gunicorn HOTEL_BBL_POST_INSERT_BusinessBlock.py
worker: gunicorn HOTEL_BBL_POST_INSERT_BusinessBlockDefinite.py
worker: gunicorn HOTEL_BBL_POST_INSERT_GroupCancel.py
worker: gunicorn HOTEL_BBL_POST_INSERT_GroupReservation.py
worker: gunicorn HOTEL_BBL_POST_SELECT_Business_Block_activitylog.py
worker: gunicorn HOTEL_BBL_POST_SELECT_QueryGroupCancel.py
worker: gunicorn HOTEL_BBL_POST_UPDATE_Business_Block_Update.py
worker: gunicorn HOTEL_CAH_GET_SELECT_QUERYINSHOUSERECORD.py
worker: gunicorn HOTEL_BBL_POST_UPDATE_BusinessBlockStatus.py
worker: gunicorn HOTEL_BBL_POST_UPDATE_UpdateGrid.py
worker: gunicorn HOTEL_BBL_POST_UPDATE_BusinessBlockDefinite.py
worker: gunicorn HOTEL_BBL_POST_SELECT_QueryRoomRevenue.py
worker: gunicorn HOTEL_BBL_POST_SELECT_QueryGrid.py
worker: gunicorn HOTEL_BBL_POST_INSERT_Grid.py
worker: gunicorn HOTEL_BBL_POST_INSERT_CalculateRoomRevenue.py
worker: gunicorn HOTEL_BBL_POST_INSERT_PayMasterReservation.py
worker: gunicorn HOTEL_BBL_GET_SELECT_QueryDrodown.py
worker: gunicorn HOTEL_BBL_POST_SELECT_EditBusinessBlockSearch.py
worker: gunicorn HOTEL_PAC_POST_INSERT_Package_dropdowns.py
worker: gunicorn HOTEL_PAC_POST_SELECT_Package_dropdowns.py
worker: gunicorn HOTEL_PAC_POST_INSERT_Package_Code.py
worker: gunicorn HOTEL_PAC_POST_UPDATE_Package_Code.py
worker: gunicorn HOTEL_PAC_POST_DELETE_Package_Code.py
worker: gunicorn Hotelpmsreport.py
worker: gunicorn HOTEL_AR_POST_INSERT_AccountSetup.py
worker: gunicorn HOTEL_AR_POST_INSERT_ArNotes.py
worker: gunicorn HOTEL_AR_POST_INSERT_Account_Traces.py
worker: gunicorn HOTEL_AR_POST_INSERT_AccountInvoice.py
worker: gunicorn HOTEL_AR_POST_SELECT_Activitylog.py
worker: gunicorn HOTEL_AR_POST_INSERT_CompressInvoice.py
worker: gunicorn HOTEL_AR_POST_INSERT_ReasonDropdown.py
worker: gunicorn HOTEL_AR_POST_INSERT_ARTransfer.py
worker: gunicorn HOTEL_RES_POST_INSERT_AttachAcompanyingGuest.py
worker: gunicorn HOTEL_RES_POST_Insert_RoomRouting.py
worker: gunicorn Hotel_RM_Post_SELECT_OccupancyGraph.py
worker: gunicorn hotel_rm_post_Select_Turndown_management.py
worker: gunicorn Hotel_END_OF_Day_POST_countrycheck.py
clock: python clock.py
